2. Create a new file called secret.yaml and add it to the template folder. Add the following content to the file:

apiVersion: v1
kind: Secret
metadata:
  name: simpleapp-secret
data:
  Y-KEY: {{ .Values.secret | quote | b64enc }}
